spring:
  application:
    name: shipments-service
  datasource:
    url: jdbc:mysql://localhost:3333/ecommerce_shipments_db?&useSSL=false&allowPublicKeyRetrieval=true
    username: ${SPRING_DATASOURCE_USERNAME:davidking}
    password: ${SPRING_DATASOURCE_PASSWORD:davidking!!}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

server:
  port: 8003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrl: https://${eureka.hostname}/info
    healthCheckUrl: https://${eureka.hostname}/health
    homePageUrl: https://${eureka.hostname}/

shipment:
  address:
    wasNull: Shipment Address was null or missing, required to create Shipment
  account:
    wasNull: Shipment Account was null or missing, required to create Shipment
  required:
    fieldSuffix: ",required."
