spring:
  application:
    name: shipments-service
  datasource:
    url: jdbc:mysql://${mysqldocker.shipments.container.name:localhost}:3306/ecommerce_shipments_db?&useSSL=false&allowPublicKeyRetrieval=true
    username: ${SPRING_DATASOURCE_USERNAME:davidking}
    password: ${SPRING_DATASOURCE_PASSWORD:davidking!!}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

server:
  port: 8003

eureka:
  instance:
    hostname: shipments-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka

# docker custom variables
mysqldocker:
  accounts:
    container:
      name: accounts_mysql_container
  orders:
    container:
      name: orders_mysql_container
  products:
    container:
      name: products_mysql_container
  shipments:
    container:
      name: shipments_mysql_container

shipment:
  address:
    wasNull: Shipment Address was null or missing, required to create Shipment
  account:
    wasNull: Shipment Account was null or missing, required to create Shipment
  required:
    fieldSuffix: ",required."
