apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-shipments-persvol
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  local:
    path: /data/db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - localhost